---
- name: Deploy DFIR-IRIS Case Management System
  hosts: data_services
  become: yes
  tasks:
    - name: Create IRIS directory structure
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - /opt/iris
        - /opt/iris/postgres
        - /opt/iris/uploads

    - name: Create IRIS Docker Compose configuration
      copy:
        content: |
          version: '3.8'
          services:
            iris-db:
              image: postgres:13
              container_name: iris-db
              restart: unless-stopped
              environment:
                POSTGRES_DB: iris
                POSTGRES_USER: iris
                POSTGRES_PASSWORD: iris_secure_password
                POSTGRES_HOST_AUTH_METHOD: scram-sha-256
                POSTGRES_INITDB_ARGS: --auth-host=scram-sha-256
              volumes:
                - postgres_data:/var/lib/postgresql/data
              ports:
                - "5432:5432"

            iris-redis:
              image: redis:7
              container_name: iris-redis
              restart: unless-stopped

            iris-web:
              image: dfirtrack/iris-web:latest
              container_name: iris-web
              restart: unless-stopped
              depends_on:
                - iris-db
                - iris-redis
              ports:
                - "8000:8000"
              environment:
                POSTGRES_SERVER: iris-db
                POSTGRES_PORT: 5432
                POSTGRES_DB: iris
                POSTGRES_USER: iris
                POSTGRES_PASSWORD: iris_secure_password
                REDIS_SERVER: iris-redis
                REDIS_PORT: 6379
                SECRET_KEY: "iris-secret-key-change-this"
                SECURITY_PASSWORD_SALT: "iris-salt-change-this"
                CELERY_BROKER_URL: redis://iris-redis:6379/0
                CELERY_RESULT_BACKEND: redis://iris-redis:6379/1
                IRIS_UPSTREAM_SERVER: iris-web
                IRIS_UPSTREAM_PORT: 8000
                DOCKERIZED: 1
              volumes:
                - uploads_data:/home/iris/downloads
                - /data/cases:/home/iris/cases:ro

            iris-worker:
              image: dfirtrack/iris-web:latest
              container_name: iris-worker
              restart: unless-stopped
              depends_on:
                - iris-db
                - iris-redis
              environment:
                POSTGRES_SERVER: iris-db
                POSTGRES_PORT: 5432
                POSTGRES_DB: iris
                POSTGRES_USER: iris
                POSTGRES_PASSWORD: iris_secure_password
                REDIS_SERVER: iris-redis
                REDIS_PORT: 6379
                SECRET_KEY: "iris-secret-key-change-this"
                SECURITY_PASSWORD_SALT: "iris-salt-change-this"
                CELERY_BROKER_URL: redis://iris-redis:6379/0
                CELERY_RESULT_BACKEND: redis://iris-redis:6379/1
                DOCKERIZED: 1
              command: ['celery', '--app=app.celery', 'worker', '--loglevel=INFO']
              volumes:
                - uploads_data:/home/iris/downloads
                - /data/cases:/home/iris/cases:ro

          volumes:
            postgres_data:
            uploads_data:
        dest: /opt/iris/docker-compose.yml

    - name: Start IRIS services
      command: docker-compose up -d
      args:
        chdir: /opt/iris

    - name: Wait for IRIS to be ready
      wait_for:
        host: localhost
        port: 8000
        delay: 60
        timeout: 600

    - name: Display IRIS access information
      debug:
        msg: |
          DFIR-IRIS is now accessible at: http://10.128.0.19:8000
          
          Initial setup requires creating an admin user.
          Navigate to the URL above to complete setup.