---
- name: Deploy TheHive Case Management (Alternative to IRIS)
  hosts: data_services
  become: yes
  tasks:
    - name: Create TheHive directory structure
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - /opt/thehive
        - /opt/thehive/data
        - /opt/thehive/index

    - name: Create TheHive Docker Compose configuration
      copy:
        content: |
          version: '3.8'
          services:
            elasticsearch:
              image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
              container_name: thehive-elasticsearch
              restart: unless-stopped
              environment:
                - http.host=0.0.0.0
                - discovery.type=single-node
                - cluster.name=hive
                - script.allowed_types=inline
                - thread_pool.search.queue_size=100000
                - thread_pool.write.queue_size=10000
                - gateway.recover_after_nodes=1
                - xpack.security.enabled=false
                - bootstrap.memory_lock=true
                - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
              ulimits:
                memlock:
                  soft: -1
                  hard: -1
                nofile:
                  soft: 65536
                  hard: 65536
              volumes:
                - elasticsearch_data:/usr/share/elasticsearch/data
              ports:
                - "9201:9200"

            thehive:
              image: strangebee/thehive:5.2
              container_name: thehive
              restart: unless-stopped
              depends_on:
                - elasticsearch
              ports:
                - "9000:9000"
              environment:
                - JVM_OPTS="-Xms1024M -Xmx1024M"
              command: |
                --no-config
                --no-config-secret
                --secret "TheHive-Secret-Key-Change-This"
                --cql-hostnames elasticsearch
                --index-backend elasticsearch
                --es-hostnames elasticsearch
                --es-index-name thehive
                --cluster-name hive
              volumes:
                - thehive_data:/opt/thp/thehive/data
                - thehive_index:/opt/thp/thehive/index
                - /data/cases:/opt/thp/thehive/cases

          volumes:
            elasticsearch_data:
            thehive_data:
            thehive_index:
        dest: /opt/thehive/docker-compose.yml

    - name: Start TheHive services
      command: docker-compose up -d
      args:
        chdir: /opt/thehive

    - name: Wait for TheHive to be ready
      wait_for:
        host: localhost
        port: 9000
        delay: 60
        timeout: 600

    - name: Display TheHive access information
      debug:
        msg: |
          TheHive is now accessible at: http://10.128.0.19:9000
          
          Initial setup:
          1. Navigate to the URL above
          2. Create an admin user during first login
          3. Configure organization settings
          
          Note: Cases will be stored in /data/cases for integration with forensics tools.
